panther-labs/panther_analysis_tool

README.md
Now that we've successfully uploaded the `panther_analysis_tool` to pip, I've updated the installation instructions to guide people to pip as the primary installation source.
* Updated installation instructions in README
* N/A
=> Updated the installation instructions

panther_analysis_tool/main.py, requirements.txt, setup.py
I screwed up a few things in the last release:
* Put in the wrong download URL
* Didn't update the self reported version number
* Committed some development dependencies
This change is to fix these issues.
* Fixed packaging issues of 0.2.0 release
* Locally
=> Fixed packaging issues

Makefile, panther_analysis_tool/main.py, setup.py
This change adds better exception handling to the `panther_analysis_tool` so you won't get dumped to a help message when processing bad python/YAML quite so often.
Additionally, this change adds better support for filtering based on tags or any other field that accepts a list of values.
* Adds generic exception handling to:
* Loading & validating specification files
* Executing policy/rule tests
* Running the main script body
* Adds better filtering for fields that contain lists
* Previously if a field contained a list, that filter would have to specify EVERY value in that list to be considered a match. Now only one field needs to be specified
* Unit tests
* Manual testing of a few known issues
* Filtering based on tags
```
% panther_analysis_tool test --path aws_redshift_policies …
```
=> added better exception handling & filtering

.github/CODEOWNERS
=> Remove Jack from CODEOWNERS

panther_analysis_tool/main.py, panther_analysis_tool/schemas.py, setup.py, tests/fixtures/valid_analysis/rules/example_rule.yml
Add  threshold field for rules.
* Allow rules to specify a threshold
* Unit testing
=> add threshold

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/story.md
* Check-in the ISSUE templates from our other repos
* Update the CODEOWNERS to reflect the current sec eng team
=> [git] issue templates

panther_analysis_tool/main.py, setup.py
Update 0.4.0 release information.
* Update version to 0.4.0
*  N/A
=> 0.4.0 release

panther_analysis_tool/test_case.py, tests/fixtures/valid_analysis/rules/example_rule.py
Support use of the `in` keyword for unit tests.
* Add python `__contains__` magic function
* Wrote a unit tests that uses `in` in a rule
=> Add contains function

panther_analysis_tool/main.py, setup.py
Bump to 0.4.5 to include latest data model fixes.
* Change version numbers
* None
=> Bump versions

LICENSE.txt, README.md, panther_analysis_tool/__init__.py, panther_analysis_tool/main.py, panther_analysis_tool/schemas.py, setup.py
Change the license to AGPLv3
* `pip-licenses` reflects the change
=> Update license to AGPLv3

panther_analysis_tool/main.py, setup.py
Updating versions for the 0.5.0 release.
* Updated version strings
=> v0.5.0 release

panther_analysis_tool/main.py, requirements.txt, setup.py
Change how the AWS profile is set.
* Change how the AWS profile is set
* Local testing
=> Update profile logic

panther_analysis_tool/main.py
Adding missing path
* add query path
* uploaded zip with queries
=> add query path

panther_analysis_tool/main.py, setup.py
Prepping for version 0.5.3.
* Bump versions
* None
=> New version

panther_analysis_tool/main.py, setup.py
Cutting new v0.7.0 release
* Version bump
=> Release 0.7.0

panther_analysis_tool/data_model.py, panther_analysis_tool/enriched_event.py, panther_analysis_tool/exceptions.py, panther_analysis_tool/immutable.py, panther_analysis_tool/log_schemas/user_defined.py, panther_analysis_tool/main.py, panther_analysis_tool/schemas.py, panther_analysis_tool/util.py
Relates to: https://app.asana.com/0/1200375859137994/1200375859138031/f
Need to update list of supported logtypes.
* Update regex list
* built + ran against detections with these types.
=> add zendesk + github logtypes

README.md
Clarify that Panther accepts PRs from forks.
* Added sentence and link in README explaining PR process
* n/a
=> Add a link to Github PR instructions

panther_analysis_tool/main.py
Data models don't work when a filter is provided.
* Make data models work with filters
* local manual testing
=> Fix datamodels filters

panther_analysis_tool/main.py
It seems we're not correctly setting an environment variable when using the update-schemas command.
* Set env variable correctly
* None
=> Set session profile

.github/CODEOWNERS
Add Dan as codeowner for PR reviews etc.
* Add @danbiwer  to CODEOWNERS
* N/A
=> Add Dan B as code owner

panther_analysis_tool/detection.py, panther_analysis_tool/log_schemas/user_defined.py, panther_analysis_tool/main.py, panther_analysis_tool/rule.py, tests/unit/panther_analysis_tool/test_rule.py
Relates to: https://app.asana.com/0/1199961856165998/1200617586832916/f
* rename rule_* to detection_*
* return DetectionResult from rule.run()
* `make test`
* `make integration`
=> transition to DetectionResult

.github/CODEOWNERS
I like to own things.  Also talking with Nick he agreed that it made sense for me to work on this tool as well
* Added myself to CODEOWNERS
* I ensured I am who I say I am
=> Add Ben as Codeowner

.circleci/config.yml, .github/CODEOWNERS, Pipfile.lock, panther_analysis_tool/main.py
Adds more members of the team to simplify merges
=> adds Dar and Nic to code owners

panther_analysis_tool/schemas.py
New Log Type for Atlassian
Added Atlassian to Log Regex
Unit tests
=> Add Atlassian to log regex

panther_analysis_tool/schemas.py
Add support for Asana Logs
Add Asana.Audit to schemas.py
Lint, format and unit tests
=> Add Asana Audit to schemas

Pipfile.lock, panther_analysis_tool/log_schemas/user_defined.py, panther_analysis_tool/lookup_tables/lookup_table.py, panther_analysis_tool/main.py, panther_analysis_tool/schemas.py, setup.py, tests/fixtures/custom-schemas/valid/lookup-table-schema-1.yml, tests/fixtures/lookup-tables/invalid/lookup-table-1.yml, tests/fixtures/lookup-tables/valid/lookup-table-1.yml, tests/fixtures/lookup-tables/valid/lookup-table-2.yml, tests/fixtures/lookup-tables/valid/sample_aws_accounts.csv, tests/unit/panther_analysis_tool/log_schemas/test_user_defined.py, tests/unit/panther_analysis_tool/test_lookup_tables.py, tests/unit/panther_analysis_tool/test_main.py
It will be helpful for PAT users to be able to perform basic CRUD operations with Lookup Tables.
* Added a new lookup_table.py file for the core LUT functionality
* A CLI entrypoint in main.py
* Tests and samples
* Unit tests
=> Add Lookup Table upload support to PAT

panther_analysis_tool/schemas.py
Need to support new log source
Updated Log Regex
Unit tests
=> Add Panther Audit Logs to regex

panther_analysis_tool/backend/client.py, panther_analysis_tool/backend/graphql/bulk_upload.graphql, panther_analysis_tool/backend/public_api_client.py
Adds bulk upload support via the api token
* Adds real implementation for the public api client around bulk uploads
=> adds public api bulk upload support

panther_analysis_tool/schemas.py, tests/fixtures/lookup-tables/valid/lookup-table-1.yml
Now users can upload lookup table content by specifying it in the FileName field. The DataFile field were a breadcrumbs from previous implementations which is not included here. Supporting of new file extensions is added as well (WIP)
* Add a new field to the schema (instead of an obsolete one)
* Unit test is edited to match code changes 
* I checked manually that uploading works
=> Update Lookup Table schema with a new field

panther_analysis_tool/main.py, setup.py
Bumping to new version to include new changes
* new changes can be found here: https://github.com/panther-labs/panther_analysis_tool/pull/205
* Make test in venv was successful as was test update
=> Update version to 0.15.1

setup.py
Increment version number for release 1.16
=> inc version to 16

panther_analysis_tool/main.py, setup.py
=> Danbiwer inc version 16

panther_analysis_tool/schemas.py
=> microsoft graph schema

panther_analysis_tool/main.py, setup.py
Prep for release
* update version
* `make test`
=> version bump

.github/workflows/ci.yml, Pipfile, Pipfile.lock, panther_analysis_tool/backend/client.py, panther_analysis_tool/backend/lambda_client.py, panther_analysis_tool/backend/mocks.py, panther_analysis_tool/backend/public_api_client.py, panther_analysis_tool/cmd/bulk_delete.py, panther_analysis_tool/cmd/check_connection.py, panther_analysis_tool/cmd/panthersdk_test.py, panther_analysis_tool/cmd/panthersdk_upload.py, panther_analysis_tool/cmd/panthersdk_utils.py, panther_analysis_tool/cmd/standard_args.py, panther_analysis_tool/enriched_event.py, panther_analysis_tool/log_schemas/user_defined.py, panther_analysis_tool/main.py, panther_analysis_tool/util.py
Autocommit formatting in CI
* ran `make fmt`
=> maxrichmond: fmt

README.md
Make it easier to develop PAT
* Add local development section to readme
* tested the steps locally
=> Adding local development section to readme

panther_analysis_tool/main.py, panther_analysis_tool/zip_chunker.py, tests/unit/panther_analysis_tool/test_main.py
We added support for batching by type in #235. This PR builds on that one by breaking our batches down further .. and also introduces a max_size parameter to the ZipChunk data class.
* exists early if any batch fails and returns appropriate error code
* adds optional max_size parameter to the ZipChunk data class
* updates ChunkFiles class to handle parent child relationships between yml files and their related files
* Splits batch 1 into 3 more batches ... batches are now:
- data models & globals
- rules
- policies
- queries
- scheduled rules
- look up tables
* adds max size to most batches: e.g.
- rules = 200
- policies = 200
- queries = 100
- scheduled rules = 200
- lookup tables = 100 
* Unit tests
* Manual tests
```
[INFO]: Zipping analysis items in . to .
[INFO]: Uploading Batch 1... …
```
=> breaks uploads into smaller batches when using the --batch parameter

panther_analysis_tool/schemas.py
update log type regex for PAT w/ some recently added logtypes.
* Add Snyk.* log types
* Add Sentinel One Deep Visibility V2 schema
I am unfamiliar w/ testing w/ this repo. Do we have unit tests to verify that these schemas properly get detected?
=> update log types regex

panther_analysis_tool/schemas.py
Add GCP HTTP Load Balanacer logs to regex
=> add gcp http load balancer log to regex

panther_analysis_tool/schemas.py
Updating schemas.py to include Auth0.Events. This fixes the [issue](https://panther-labs.slack.com/archives/C026QGU2UG4/p1684426840916579) raised by Andy in Slack.
Closes https://app.asana.com/0/1204556313175377/1204623081932042
=> Updating schemas.py to include Auth0.Events

panther_analysis_tool/analysis_utils.py, panther_analysis_tool/constants.py, panther_analysis_tool/main.py, panther_analysis_tool/validation.py
We have been using a map but treating it as a class. We have been using a collection of constant strings to interact with that map. This has lead to more error prone code that is harder to read.
* Creates `ClassifiedAnalysisContainer` class to replace map
* Namespaces all analysis type constants under `AnalysisTypes` class
* All existing tests pass
* panther-analysis tests all still pass
* Uploading panther-analysis works
* Uploading panther-analysis in batches works
=> refactoring: classified analysis container

panther_analysis_tool/schemas.py
https://app.asana.com/0/1204526398494609/1204727935992623/f
=> Add Netskope to schema

panther_analysis_tool/detection_schemas/simple_detection_json_schema.json, panther_analysis_tool/schemas.py, tests/fixtures/inline-filters/basic.python.rule.with.filters.yml, tests/fixtures/inline-filters/basic.rule.with.filters.yml, tests/fixtures/simple-detections/valid/test.enrichment.rule.yml, tests/fixtures/simple-detections/valid/test.rule.with.dynamic.funcs.yml
Now that dynamic functions, KeyPath, and Enrichments have been implemented on the backend, we can add the new schema here.
* Adds new fields to rule schema code
* Adds new json schema from PE
* Existing tests pass
* New test files added
* Works with current PA
=> updated schemas

panther_analysis_tool/schemas.py
new schema coming in
https://github.com/panther-labs/panther-enterprise/pull/13771
* update schemas.py w/ new schema name
=> Add Heroku.Runtime

panther_analysis_tool/schemas.py
Added Windows event logs to schemas.py. This doesn't need to go live until after next week.
Closes: https://app.asana.com/0/1204556313175377/1205041300643919/f
=> Windows Event Logs

panther_analysis_tool/schemas.py
closes: https://app.asana.com/0/1204556313175377/1205068092060524/f
=> Adding Linux.Auditd

panther_analysis_tool/schemas.py
closes: https://app.asana.com/0/1204556313175377/1205128261265695/f
=> add docker events schema to logtype regex

panther_analysis_tool/schemas.py
add the azure schemas to the logtype regex
closes: https://app.asana.com/0/1204556313175377/1205131351101724/f
=> add azure schemas to logtype regex

panther_analysis_tool/schemas.py
closes: https://app.asana.com/0/1204556313175377/1204918017402432/f
=> Adding Carbon Black

panther_analysis_tool/schemas.py
closes: https://app.asana.com/0/1204556313175377/1205087522481693/f
=> adding Tenable.Vulnerability

panther_analysis_tool/command/benchmark.py
A few small tweaks to the formatting of the output file for the benchmark subcommand, easier to work with and read
=> Prettify output file for benchmark

panther_analysis_tool/schema_regexs.py
=> add envoy access log type

.gitignore
I don't want someone to accidentally commit it. It makes sense to me to always have it git ignored.
=> add .panther_settings.yml to .gitignore

Pipfile, Pipfile.lock, requirements.txt
#366 and #367 can close in favor of this
=> Version bump for requests and sqlfluff

README.md
=> README makeover

.github/workflows/test_release_publish.yml
Adding `dist` path for gh release create
=> Adding dist path for release gha

.github/workflows/test_release_publish.yml
* adding --draft flag to gh release create
=> Adding Draft flag to push PR

.github/workflows/version_bump_pr.yml
* Adding allow listed username for CLA
=> Adding [bot] to dac-bot for CLA

Pipfile, Pipfile.lock, panther_analysis_tool/detection_schemas/analysis_config_schema.json, panther_analysis_tool/main.py, panther_analysis_tool/schemas.py
Rules can now have a CreateAlert field that defaults to True. When set to False, it will suppress the alert and create a signal instead. 
* Adds CreateAlert to schemas for validation
* Hides all dynamic alert funcs from test output except for the alert context
* All current tests pass
* Manually tested test and upload with the new field
Example output of upload cmd:
```bash
/Users/mcr/.local/share/virtualenvs/max-pa-0qsMSnqL/bin/pat:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
__import__('pkg_resources').require('panther-analysis-tool==0.36.0')
[INFO][root]: Found Environment Variables prefixed with 'PANTHER'.
[INFO][root]: Panther Public API endpoint: https://rmbm7y7318.execute-api.us-west-2.amazonaws.com/v1/publ …
```
=> CreateAlert support

Pipfile, Pipfile.lock, panther_analysis_tool/detection_schemas/analysis_config_schema.json, panther_analysis_tool/main.py, panther_analysis_tool/schemas.py
**Background**
This PR appears to be causing issues. Reverting until we can get to the bottom of the specific issue it is causing
Reverts panther-labs/panther_analysis_tool#431
=> Revert "CreateAlert support"

requirements.txt, setup.py
We recently updated this panther-core version to be >= .. which is causing probs. We want this to be a fixed panther-core version moving forward
=> fixes panther-core version.

Pipfile, Pipfile.lock
=> updates versions for release

Makefile, Pipfile.lock, requirements.txt
We made some changes to panther core that PAT will need in the next enterprise release.
* Updates panther-core to 0.8.1
=> updates panther-core to 0.8.1

panther_analysis_tool/analysis_utils.py
=> fix: yaml referenced before assignment

panther_analysis_tool/analysis_utils.py
package.json files are being added to PA and need to be ignored
* added default values to the normalized ignore list.
=> adding default ignore files for package.json

Pipfile, Pipfile.lock, panther_analysis_tool/analysis_utils.py, panther_analysis_tool/backend/client.py, panther_analysis_tool/backend/lambda_client.py, panther_analysis_tool/backend/public_api_client.py, panther_analysis_tool/log_schemas/user_defined.py, panther_analysis_tool/schemas.py, panther_analysis_tool/testing.py, tests/unit/panther_analysis_tool/test_analysis_utils.py, tests/unit/panther_analysis_tool/test_check_packs.py, tests/unit/panther_analysis_tool/test_main.py, tests/unit/panther_analysis_tool/test_testing.py
Bumps black formatter and reformats the python files.
Follow up of #471 
* Bumps black and reformats the code
* CI
=> Bump black from 23.7.0 to 24.3.0

panther_analysis_tool/detection_schemas/analysis_config_schema.json
We now support a new top-level field for correlation rules: MinMatchCount. Updating schema to allow this field
* update schema
* uploaded a correlation rule with MinMatchCount, it uploaded successfully
=> EPD-695 minmatch schema update

panther_analysis_tool/main.py
check_packs is erroring on correlation rules https://github.com/panther-labs/panther-analysis/actions/runs/10375052896/job/28723878179#step:7:31
* update check_packs to work with correlation rules
* make test
=> Update check_packs for CRs

.github/workflows/ci.yml, .github/workflows/fmt.yml, .github/workflows/test_release_publish.yml, .github/workflows/version_bump_pr.yml
Removes step-security from GHAs
=> remove step security

panther_analysis_tool/main.py
A few small QoL improvements to pat output!
* Simplified the base logging config (to remove the ROOT)
* Made the upload summary pretty
* Fixed the newline in the versioning message
New sample output:
```bash
$ pipenv run pat upload --path queries/aws_alb_queries --max-retries 2  --ignore-table-names
INFO: Found config file .panther_settings.yml (note: command line options will override config file settings)
INFO: Panther Public API endpoint: https://7sr3meamic.execute-api.us-west-2.amazonaws.com/v1/public/graphql
INFO: Testing analysis items in queries/aws_alb_queries
AWS.ALB.EndpointAbuse.Panther
[PASS] Abuse to web ELB
[PASS] [rule] true
[PASS] [title] High number of errored requests [36] to noflake ELBs from [3.145.213.57]
[PASS] [dedup] High number of errored requests [36] to noflake …
```
=> cleaner upload summary (with debug support), max retries arg fix, log cleanup

.github/workflows/version_bump_pr.yml
The action is now not compatible with our new requirement for all commits to be signed
* Added commits signing
* Running GHA ([result](https://github.com/panther-labs/panther_analysis_tool/pull/587))
=> THREAT-449 Fix PAT version bump action

panther_analysis_tool/detection_schemas/analysis_config_schema.json, panther_analysis_tool/schemas.py
Adding the necessary changes so that panther_analysis_tool users are able to create custom lookup tables with objects in Google Cloud Storage buckets as a backing source.
[Respective panther-enterprise backend PR](https://github.com/panther-labs/panther-enterprise/pull/23608/commits).
Closes https://panther-labs.atlassian.net/browse/EPD-3370
* change jsonschema to allow uploading the necessary values for a google cloud storage-backed custom lookup table
* add extra constraints to make sure both s3-backed and google cloud storage-backed lookup tables are properly uploaded
1. deployed required backend changes on my dev env
2. created a pat directory locally
- created `lookup_tables` folder
- created `lookup_tables/mytable.yml`
```yaml
AnalysisType: lookup_table
LookupName: mytable
Schema: …
```
=> Enable GCS LUTs

panther_analysis_tool/analysis_utils.py, panther_analysis_tool/core/parse.py, panther_analysis_tool/main.py, panther_analysis_tool/schemas.py, tests/unit/panther_analysis_tool/test_analysis_utils.py, tests/unit/panther_analysis_tool/test_main.py
Move more code out of `main.py` for better readability.
=> more refactors

panther_analysis_tool/backend/client.py, panther_analysis_tool/backend/lambda_client.py, panther_analysis_tool/cli_output.py, panther_analysis_tool/constants.py, panther_analysis_tool/util.py, panther_analysis_tool/zip_chunker.py, tests/unit/panther_analysis_tool/test_util.py
=> remove deadcode

panther_analysis_tool/detection_schemas/analysis_config_schema.json, panther_analysis_tool/schemas.py, tests/unit/panther_analysis_tool/test_schemas.py
Added a new EmailConfig optional field for scheduled_query schema
* Added a new EmailConfig optional field for scheduled_query schema
* updated unit tests
=> update schemas to support new email config
