README.md
panther_analysis_tool/main.py

We're going to be adding support soon for a reports field, which will help report generation. Since we want to move some information currently encoded in tags to the reports field, this change just allows the field to be present and not throw an error during testing. The Panther backend throws away the Reports field when processing the configuration.
* Allow a reports field to exists, which will be a map of strings (report names, which will also later be treated as tags) to objects (typically either a list of strings or a dictionary)
* Added some different configurations of report fields to some policies I'm working on locally and tested and uploaded them, no issues

Support Reports Field

---

Makefile
README.md
panther_analysis_tool/main.py
requirements.txt
setup.py
tests/unit/panther_analysis_tool/test_main.py

Updated the `panther_analysis_tool` to refer more generally to both policies and rules, where previously it was more policy centric.
* Updated `panther_analysis_tool` to refer to `analysis` or `policies and rules` in place of just `policies` both in command output and also internally
* Updated docs accordingly
* `make ci`

Update Phrasing to be more General

---

panther_analysis_tool/main.py
setup.py

Allow users to specify a `DedupPeriodMinutes` field. Currently only supported for rules. If configured for a policy, it will be ignored. 
* Adjusted expected schema
* `make ci`

Add DedupPeriodMinutes as a supported field

---

panther_analysis_tool/main.py
setup.py
tests/fixtures/valid_policies/example_rule.yml

Add support for `RuleID`, `LogType` fields in rule specifications, and `Log` and `LogType` fields in test specifications.
Closes #3.
* Added some optional fields
* Used secondary fields when primary fields where not present
* Unit testing
* Used the `upload` command to upload some rules with the new fields to my test account

Support Rule Fields

---

README.md
panther_analysis_tool/main.py
setup.py
tests/fixtures/valid_policies/example_policy.yml
tests/unit/panther_analysis_tool/test_main.py

Adds the `--filter` flag to all commands, allowing users to filter to just specific analysis objects by specifying any valid field in an analysis specification file.
Closes #5 .
Example usage:
`panther_analysis_tool test --path tests/fixtures/valid_policies --filter AnalysisType=policy,global`
- will only apply to `policy` and `global` analysis types, excluding rules
`panther_analysis_tool test --path tests/fixtures/valid_policies --filter AnalysisType=policy Severity=Critical`
- will only apply to `policy` analysis types that have the severity `Critical`
`panther_analysis_tool test --path tests/fixtures/valid_policies --filter AnalysisType=policy,global Severity=Critical,""`
- By providing an empty string, you can indicate that the field need not be present. So this will only apply to …

Add support for generic filtering

---

panther_analysis_tool/main.py
setup.py
tests/fixtures/valid_policies/example_rule.py
tests/fixtures/valid_policies/helpers.yml

When testing rules, show the title and dedup field if one is set. Closes #24 .
Added support for multiple globals, and require the `GlobalID` field in global analysis types now. Also automatically searches for globals in the default location in addition to the path specified.
* When testing rules, show the title and dedup values if one is set
* Must specify the `GlobalID` field in global analysis types now, and the `GlobalID` will be used as the module name for importing
* Automatically checks the path `global_helpers` (relative to where the command is being run from) for ANY analysis items. Recommend only putting global analysis types here.
* make ci
Example output:
```
$ panther_analysis_tool test --path tests/fixtures/valid_policies
[INFO]: Testing analysis packs in …
```

Show dedup/title values

---

panther_analysis_tool/schemas.py
tests/fixtures/valid_analysis/policies/example_policy.yml

Previously we had envisioned allowing Reports to be defined as either a map of strings to lists of strings OR a map of strings to maps of strings to strings. We have since consolidated on just the first definition on the backend, but the `panther_analysis_tool` needs to be updated to reflect that.
* Only allow reports to be maps of strings to lists
* Manual testing

Fix report parsing

---

README.md

Simple bug fix of `ResourceType`/`LogType` field name in README examples

Fix ResourceType/LogType field name in README examples

---

README.md
panther_analysis_tool/main.py
panther_analysis_tool/schemas.py
setup.py
tests/fixtures/aws_globals.yml
tests/fixtures/example_malformed_policy.yml
tests/fixtures/example_policy.yml
tests/fixtures/example_policy_import.yml
tests/fixtures/valid_analysis/policies/example_policy_beta.yml
tests/fixtures/valid_analysis/policies/example_policy_extraneous_fields.yml
tests/fixtures/valid_analysis/rules/example_rule.yml
tests/fixtures/valid_analysis/rules/example_rule_extraneous_fields.yml

**WIP:** 
We should communicate the Panther version after which the policy/rule tests can be deployed without the extra fields.
I have added a TODO in the README to note it there at least.
Will work on the analysis-api now so that it can handle tests without these fields and after we merge that and know to which Panther version it will be included, we can get back and merge this one.
The ResourceType (in policy tests) and LogType (in rule tests) fields are not
necessary since they can be inferred from the policy/rule under test.
The tool can parse older policies/rules that include these fields.
However, this is a backwards-incompatible change for the analysis-api, so
the fields must be present in the tests when deploying them to older Panther versions.
See …

Cleanup unneeded ResourceType/LogType fields in policy/rule tests

---

panther_analysis_tool/main.py
tests/fixtures/valid_analysis/rules/example_rule.py
tests/unit/panther_analysis_tool/test_main.py

No longer prints the help message unless the user runs the tool with `--help` or `-h`. 
* No longer print the help messages unless specifically requested
* If a rule/policy raises an exception report this as a failed test
* Unit testing

Fixed up some unexpected behavior

---

panther_analysis_tool/main.py
panther_analysis_tool/schemas.py
tests/fixtures/valid_analysis/policies/example_policy.yml

@s0l0ist added support for destination overrides in Panther including in the BulkUpload API, so we should allow users to define this field when managing policies or rules from the commandline.
* Add `OutputIds` as an optional field to policies and rules. This field is a list of strings, where each string is the ID of a destination. In a future iteration, we might allow users to specify a destination name that is then mapped to the corresponding destination ID by either the CLI tool or the backend
* Fixed some linting/typing issues `make ci` found 
* Unit tests

Add support for destination overrides

---

panther_analysis_tool/main.py
tests/fixtures/example_rule.py
tests/fixtures/example_rule_missing_field.yml
tests/fixtures/valid_analysis/rules/example_rule.yml
tests/unit/panther_analysis_tool/test_main.py

Overall test cases were passing even if the dedup/title functions returned None. Closes #18 
* Added ability for overall test to fail if the dedup or title function return None
* Update output of manually running to show dedup/title check status
* Added passing and failing unit tests. 
Example Output
Original Format:
```
% panther_analysis_tool test --path ./tests/fixtures/valid_analysis
[INFO]: Testing analysis packs in ./tests/fixtures/valid_analysis
...
AWS.CloudTrail.MFAEnabled
[PASS] Root MFA not enabled fails compliance
[PASS] User MFA not enabled fails compliance
```
New Format:
```
% panther_analysis_tool test --path ./tests/fixtures/valid_analysis
[INFO]: Testing analysis packs in ./tests/fixtures/valid_analysis
...
AWS.CloudTrail.MFAEnabled
[PASS] Root MFA not enabled fails …
```

Lindseyw test dedup title

---

.github/CODEOWNERS
panther_analysis_tool/main.py
requirements-top-level.txt
requirements.txt
setup.py

Previously, testing a directory which only contained globals would return an error. This is turn meant that you could not zip or upload just a directory of globals, as Pat first attempts to test any analysis before zipping or uploading.
Since you should still be able to test just globals (simply by validating their specification files), and since you should certainly be able to package and upload just globals, I updated Pat to accept a directory containing only globals for any operation.
* Only return a "nothing to test" error if there are no policies, rules, OR globals
* None

Allowing packaging of just globals

---

panther_analysis_tool/schemas.py
tests/fixtures/example_policy_invalid_characters.py
tests/fixtures/example_policy_invalid_characters.yml
tests/unit/panther_analysis_tool/test_main.py

Added imports And, Regex from schemas. Added character validation for DisplayName, GlobalID, PolicyID, and RuleID
Panther does not accept certain special characters in display names, such as:
'
"
&
,
and perhaps others. The panther_analysis_tool should warn against these characters when they are present in a displayname.
All changes, with the exception of related testing, that have been made are specific to the `panther_analysis_tool/schemas.py` file.
Created a new global variable `NAME_ID_VALIDATION_REGEX` which is meant to check against strings to ensure the string only contains alphanumeric characters along with dashes, underscores, periods, and spaces.
For GLOBAL_SCHEMA, POLICY_SCHEMA, and RULE_SCHEMA, the schema definition for the fields DisplayName, GlobalID, PolicyID, and RuleID …

#37 - Display Name Validation

---

panther_analysis_tool/main.py

Running `panther_analysis_tool` without arguments would throw an error. This change causes it to print the help output rather than an exception.  Closes #47 
* update to the args passed to parse_args so that if no args are passed in it will print help output. 
* `make ci`
* manual testing
Sample Output:
```
usage: panther_analysis_tool [-h] [--version] {test,zip,upload} ...
Panther Analysis Tool: A command line tool for managing Panther policies and
rules.
positional arguments:
{test,zip,upload}
test             Validate analysis specifications and run policy and rule
tests.
zip              Create an archive of local policies and rules for
uploading to Panther.
upload           Upload specified policies and rules to a Panther
deployment.
optional arguments:
-h, --help         show this …
```

print help output when running tool with no args

---

panther_analysis_tool/main.py
tests/fixtures/valid_analysis/rules/example_rule_extraneous_fields.yml
tests/unit/panther_analysis_tool/test_main.py

This updates the directory walking logic so that running the `panther_analysis_tool` will test any policies/rules in the current dir as well as those within sub directories.  Closes #41 
* update to directory walking structure
* new test case for `--path ./` and default (no `--path` option specified)
* `make ci`

test files current dir

---

panther_analysis_tool/main.py
requirements-top-level.txt
requirements.txt
setup.py
tests/fixtures/example_malformed_yaml.yml
tests/fixtures/example_strict_invalid_yaml.yml
tests/unit/panther_analysis_tool/test_main.py

The `panther_analsys_tool` isn't validating yaml as vigorously as the panther backed. We should add invalid yaml files to the invalid_specs when running `panther_analysis_tool test` Closes #32 
* Added exception handling to the json.loads and yaml.safe_load calls so that any yaml or json file that fails to load will be added to the `invalid_specs` file
* Added new invalidly formatted yaml file `example_malformed_yaml.yml` and updated tests to include additional invalid spec  
* `make test`

Update to yaml verification

---

panther_analysis_tool/main.py
tests/unit/panther_analysis_tool/test_main.py

Add ability to set aws profile as a command line arg to the `upload` command.
* new optional arg added to the upload subparser
* unit test for env variable setting
* `make ci` 
* manual testing
Update Help Menu:
```
usage: panther_analysis_tool upload [-h] [--aws-profile AWS_PROFILE]
[--path PATH] [--out OUT]
[--filter KEY=VALUE [KEY=VALUE ...]]
[--debug]
optional arguments:
-h, --help            show this help message and exit
--aws-profile AWS_PROFILE
The AWS profile to use when uploading to an AWS
Panther deployment.
--path PATH           The relative path to Panther policies and rules.
--out OUT             The location to store a local copy of the packaged
policies and rules.
--filter KEY=VALUE [KEY=VALUE ...]
--debug
```
Updated output:
```
...
[INFO]: Using AWS profile: …
```

aws profile as a command line arg

---

README.md
tests/fixtures/example_unhandled_exception.py
tests/fixtures/example_unhandled_exception.yml
tests/unit/panther_analysis_tool/test_main.py

Validate that tests that caused an unknown exception get added to the failed test list.  Closes #29 
* Added test case to validate exception throwing test causes `panther_analysis_tool test` to return non-zero exit 
* `make ci`

non loading error

---

panther_analysis_tool/main.py
tests/unit/panther_analysis_tool/test_main.py

`SchemaWrongKeyError` output can be extremely verbose.  Simplify the output by showing exactly what key triggered the error and what keys are expected.  Closes #42 
* Catching the particular exception and handling it separately than the other schema-related errors.
* Unit test for new method.
* `make ci` 
* manual test
Updated Output:
```
Invalid Tests Summary
./tests/fixtures/valid_analysis/rules/example_rule.yml
'DisplyName', 'Referece' not in list of valid keys: [['AnalysisType', 'Enabled', 'Filename', 'RuleID', 'LogTypes', 
'Severity', Optional('Description'), Optional('DedupPeriodMinutes'), Optional('DisplayName'), Optional('OutputIds'), 
Optional('Reference'), Optional('Runbook'), Optional('SummaryAttributes'), Optional('Suppressions'), Optional('Threshold'), 
Optional('Tags'), …
```

schema wrong key error output

---

panther_analysis_tool/main.py
setup.py

The tool tries to be helpful by always including globals/data models, but this can cause them to be imported multiple times when running in current directory(imports both ./global_helpers and *global_helpers*) Because it imports multiple times and the latest release does more strict checking of analysis IDs - this will cause running `test` against the panther-analysis repo to fail.  
Update to upload payload format to take into account the new analysis-api
* Check that each file imported is unique
* upload payload update, try old format if new format fails
* `make ci` 
* run test in the panther-analysis repo: `python ../panther_analysis_tool/panther_analysis_tool/main.py test`
* confirmed upload to both panther v1.13.0 and v1.14.0 analysis-api works

spec loading multiple times

---

README.md
panther_analysis_tool/main.py
requirements.txt
tests/fixtures/example_policy_required_tests.py
tests/fixtures/example_policy_required_tests.yml
tests/fixtures/valid_analysis/policies/example_policy_extraneous_fields.py
tests/fixtures/valid_analysis/rules/example_rule_extraneous_fields.py
tests/fixtures/valid_analysis/rules/example_rule_extraneous_fields.yml
tests/unit/panther_analysis_tool/test_main.py

This change adds a new flag,  `--minimum-tests`, that allows users to specify a minimum number of unit tests per detection in order for that detection to be considered passing.
If a number greater than 1 is specified, the check also enforces at least one `ExpectedResult: True` and at least one `ExpectedResult: False` unit test.
* Add new `minimum-tests` flag
* Added unit tests
* Ran against `panther-analysis` repo
Some example outputs
(run from inside the `panther_analysis_tool` repo, after modifying one of the fixtures to have zero tests)
```
% panther_analysis_tool test --path tests/fixtures/valid_analysis --minimum-tests 1
[INFO]: Testing analysis packs in tests/fixtures/valid_analysis
AWS.IAM.MFAEnabled
No tests configured for AWS.IAM.MFAEnabled
AWS.IAM.BetaTest
[PASS] Root MFA not …
```

Allow force unit tests

---

panther_analysis_tool/main.py
setup.py

Adds the `--skip-tests` flag to the `zip` and `upload` commands. Also prepares for the `0.4.2` release.
* Add the `--skip-tests` flag to allow CI/CD pipelines to bypass tests in cases where they've already been run.
* Unit tests

Release changes

---

README.md
panther_analysis_tool/main.py
panther_analysis_tool/test_case.py
setup.py

tl;dr the `event` passed around in local testing was not of type `dict` or `Mapping`, resulting in some problems. This fixes it.
When checking for types in helpers, I ran into an issue where the `event` was not of type `dict`. So after digging, I saw that we wrapped the events in a `TestCase` class that was not a subtype of `dict`, which broke the helper I wrote. When also digging through the rules engine, I saw that we subclass our [EnrichedEvent](https://github.com/panther-labs/panther/blob/master/internal/log_analysis/rules_engine/src/enriched_event.py#L24) from `Mapping`, which allows the subtypes to easily be inferred. 
* Subclass `TestCase` from `Mapping`
* Bump version
* Update our README a little to remove unnecessary info
I installed this version locally and validated my …

Use Mapping for TestCase

---

panther_analysis_tool/main.py

In adding support for both the older and newer version of the `analysis-api` - if an error was returned from the new version it was hidden because it automatically re-tried the upload using the old format. This removes support for the old format, as users can choose which version of the `pat` to use based on what version of `panther` they have deployed. 
* removed support for the old format
* `make ci`
* manual testing

hidden error message

---

panther_analysis_tool/main.py
setup.py

Currently, if one global helper fails to load we stop loading any further global helpers. Instead, we should keep loading each global helper that we can load.
* Keep loading global helpers even if one fails to load 
* Tested in `panther-analysis` with one global that failed to load. Previous to this change multiple other globals were skipped, with this change only the failing global was skipped

Continue if one global fails

---

panther_analysis_tool/main.py

In creating a zip to upload using a filter, found that data models are not automatically included when a `--filter` is specified.  
* automatically include data models in `filter_analsyis`
* manual testing:
Before (`panther_analysis_tool test --filter Tags=mytag`):
```
--------------------------
Panther CLI Test Summary
Path: .
Passed: 221
Failed: 2
Invalid: 0
--------------------------
Failed Tests Summary
Standard.AdminRoleAssigned
['GCP - Admin Assigned', 'GSuite - Privileges Assigned', 'OneLogin - Super user permissions assigned']
Standard.BruteForceByIP
['AWS.CloudTrail - Failed Login', 'Box - Login Failed', 'GSuite - Failed Login Event', 'Okta - Failed Login', 'OneLogin - Failed Login Event']
```
After(`python ../panther_analysis_tool/panther_analysis_tool/main.py test --filter …

include data model when filtering

---

panther_analysis_tool/main.py
requirements.txt

Closes [this issue](https://github.com/panther-labs/panther/issues/2639) 
We want to implement a CLI way to update managed schemas until FE team picks up the task to expose the functionality in the UI.
* Adds `update-schemas` sub-command to fetch the available updates and choose the version to install
* Ran the task against a deployed Panther version

Add subcommand to update managed schemas

---

.gitignore
panther_analysis_tool/main.py
panther_analysis_tool/test_case.py
requirements-top-level.txt
requirements.txt

The release process should be as simple as possible.
Adding the code to package the managed schemas in PAT will help with that.
The `zip-schemas` sub-command does a shallow clone of a specific tag from the `panther-analysis` repository and packages a `manifest.yml` into a `.zip` archive to be attached to releases.  
```sh
$ panther_analysis_tool zip-schemas --release=v1.16.0
$ panther_analysis_tool zip-schemas --release=v1.16.0 --out=/tmp/
```
`--release` is a required argument for the release tag to package.
`--out` sets the output _directory_ (defaults to `.`).
* Adds `zip-schemas`  command.
* ran `zip-schemas`

Add zip-schemas command to Panther analysis tool to streamline the release process

---

panther_analysis_tool/main.py

Asana Task URL: https://app.asana.com/0/1199975676341842/1199956661047416/f
Right now if you add an extraneous field to a detection specification file, PAT will fail to load that file considering it invalid.  This is to prevent users from accidentally mistyping an optional field and having it be dropped silently. 
It would be nice if this functionality could be overwritten so that users can add custom meta data fields which don't get translated over to Panther but which can contain useful information about the detection for a given organization.
* Hacky solution to allow for configurable `ignore_extra_fields` flag
* Tested `zip` `test` and `upload` with a rule specification that was not expected

Allow Advanced PAT Users to Ignore Extra Fields

---

panther_analysis_tool/main.py
tests/unit/panther_analysis_tool/test_main.py

Asana URL: Closes https://app.asana.com/0/1199975676341842/1199956661047411/f
The `zip` command was not honoring the `out` option
* create output dir if it doesn't exist
* move the output file based on the input
* update to test to check for appropriate location of output file
* `make ci`
* manual testing with no `out` option:
```
% python panther_analysis_tool/main.py zip --path ./tests/fixtures/valid_analysis 
[INFO]: Testing analysis packs in ./tests/fixtures/valid_analysis
AWS.IAM.MFAEnabled
[PASS] Root MFA not enabled fails compliance
[PASS] User MFA not enabled fails compliance
AWS.IAM.BetaTest
[PASS] Root MFA not enabled fails compliance
[PASS] User MFA not enabled fails compliance
IAM.MFAEnabled Extra Fields
[PASS] Root MFA not enabled triggers a violation. …
```

add path to output file path

---

panther_analysis_tool/main.py
panther_analysis_tool/schemas.py
requirements.txt
tests/fixtures/example_rule_invalid_mocks.py
tests/fixtures/example_rule_invalid_mocks.yml
tests/fixtures/valid_analysis/rules/example_rule_generated_functions.py
tests/fixtures/valid_analysis/rules/example_rule_generated_functions.yml
tests/fixtures/valid_analysis/rules/example_rule_mocks.py
tests/fixtures/valid_analysis/rules/example_rule_mocks.yml
tests/unit/panther_analysis_tool/test_main.py

Asana URL: Closes https://app.asana.com/0/1199940726973098/1199936555115825/f
Mocking Support within Unit Tests have been added in Panther's Rules Engine. 
Similarly, generated alert fields are also fully supported in Panther's Rules Engine.
* Added support for mocking in unit tests
* Added support for generated alert fields (with type checking)
* General housekeeping/refactoring
* `make test --path=./test/` (custom test files)
* `make unit`
* `make integration`

Support for Mocking in Unit Tests & Generated Alert Fields

---

panther_analysis_tool/test_case.py
tests/unit/panther_analysis_tool/test_test_case.py

Addresses case-sensitive lookup support: https://app.asana.com/0/1200124882238265/1200116099665098
* `TestCase`: Add case-insensitive lookup partial support for top-level fields only.
* `TestCase`: Remove non-required overrides for the Mapping sub-class and use inherited behavior.
* Unit tests
* Executed `panther_analysis_tool test` on the latest master branch of `panther-analysis`.

Support case-insensitive lookup for test cases

---

panther_analysis_tool/main.py

https://github.com/panther-labs/panther_analysis_tool/pull/91 introduces incompatible changes between rule and policy processing. Using a plain `dict` as input for policies replicates what also happens in production.
* Use `dict` instead of `TestCase` object when running policy tests.
* Print stack traces when using `--debug` in order to allow easier debugging.
* Ran tests on current master branch of `panther-analysis`. When an error is raised and `--debug` flag is used, the stack trace is also printed.

Use Python dict for policy test input

---

panther_analysis_tool/main.py
tests/fixtures/example_set_duplicates.py
tests/fixtures/example_set_duplicates.yml
tests/unit/panther_analysis_tool/test_main.py

Closes https://app.asana.com/0/1200175800812961/1199956661047427/f
When validating the specification file of a detection, `panther_analysis_tool` does not validate that 'set' fields have unique values. 
* Added support for validating duplicates in fields where Panther expects a set instead of a list. 
* Added a test for duplicates in set fields and incremented expected invalid specs.
* `make test`
* `panther_analysis_tool zip --path=/tmp/asdf` -- See SS below

Specification file validation doesn't catch invalid sets

---

panther_analysis_tool/main.py
panther_analysis_tool/schemas.py
tests/fixtures/aws_globals.yml
tests/fixtures/example_malformed_policy.yml
tests/fixtures/example_policy.json
tests/fixtures/example_policy.yml
tests/fixtures/example_policy_bad_resource_type.py
tests/fixtures/example_policy_bad_resource_type.yml
tests/fixtures/example_policy_import.yml
tests/fixtures/example_policy_missing_policy_file.yml
tests/fixtures/example_policy_required_tests.yml
tests/fixtures/example_rule_bad_log_type.py
tests/fixtures/example_rule_bad_log_type.yml
tests/fixtures/example_rule_invalid_mocks.yml
tests/fixtures/example_rule_invalid_test.yml
tests/fixtures/example_unhandled_exception.yml
tests/unit/panther_analysis_tool/test_main.py

Closes https://app.asana.com/0/1200175800812961/1199956661047407/f
The Panther backend validates the `LogTypes` and `DetectionTypes` fields, however we currently do not support this validation in `panther_analysis_tool`. This PR adds support for validating these fields to provide users more consistency and advanced warning when using `panther_analysis_tool`.
Note that any additions in Panther necessitate changes here as well -- another case where we need some type of shared libraries between the two repositories
* Added support via Regex for LogTypes and ResourceTypes
* Added flags that allow a user to ignore these validations for cases where there are custom LogTypes and ResourceTypes present
* Fixed typo `repsitory` -> `repository`
* `make test`
* Tested in local environment, see …

Support for Log Types & Resource Types Validation

---

panther_analysis_tool/main.py

Closes https://app.asana.com/0/1199906407795548/1200249363083484/f
PAT attempts to load all of the YAML and JSON files found in the specified PATH, this however includes dot-files (nix hidden folders and hidden files)
* Added conditional to skip dot-files 
* See attached SS (ignore the failing tests, those are non-related 😄 )
* Created a directory `.bad_rules` which contained a malformed detection `example_bad_rule.yml` and `example_bad_rule.py`
* Created a malformed detection in the root directory `.example_bad_rule.yml` and `.example_bad_rule.py`

Ignore Dot-Files

---

MANIFEST.in
panther_analysis_tool/main.py
setup.py

When @georgepsarakis modified the `setup.py` file, it broke new pip installs as it relied on the existence of a file that is not present in the pip package. This PR adds a manifest file which I believe indicates to pip to include this file.
* Add manifest file
* Bump to 0.6.1
* None, not sure how to test

Add requirements

---

panther_analysis_tool/main.py
tests/unit/panther_analysis_tool/test_main.py

Closes https://app.asana.com/0/1200360676535738/1200356830724953/f
Request for the ability to use `!=` for filtering tags as well as an extra optional flag to skip tests for disabled detections.
* Added inverted filtering functionality
* Added flag that allows for the skipping of tests for disabled detections
* `make test`
* `make integration`

PAT NotEQuals Filtering & Skip Test Disabled Options

---

MANIFEST.in
panther_analysis_tool/main.py
setup.py

Log schemas broke the 0.7 release
* Added log schemas to the setup.py file
* `python setup.py install` followed by `panther_analysis_tool --version`

v0.7.2 Version Bump

---

bin/panther_analysis_tool
panther_analysis_tool/__init__.py

`main.py` potentially performs global changes, such as modifying the logging configuration that could possibly affect other code that imports individual standalone modules or sub-packages.
Relates to https://app.asana.com/0/1200441743569436/1200434121289973
* Update executable program to import `main` specifically.
* CI

Allow individual modules to be imported without loading main.py

---

panther_analysis_tool/main.py

Fix a bug in test that causes the global_helpers directory to not get added to the search path when --path is not ".". This would cause tests to fail when rule had dependencies in global_helpers.
Adds each `HELPERS_LOCATION` and `DATA_MODEL_LOCATION` to search_directories - if the path exists, regardless of what --path is passed to `test`. 
- Create a rule that has a dependency in global_helpers.
- Test a specific rule (or a single directory of rules) with `panther_analysis_tool test --path path/to/rule`

Fix bug in test - add global_helpers to search dir

---

panther_analysis_tool/main.py
tests/fixtures/detections/valid_analysis/rules/example_rule_generated_functions.py
tests/unit/panther_analysis_tool/test_main.py

Add the output of `alert_context` functions to the test results
* add the output of `alert_context` to rule test results
* `make test`
```bash
% panther_analysis_tool test --filter RuleID=AWS.Root.Activity
[INFO]: Testing analysis packs in .
AWS.Root.Activity
[PASS] Root Activity - CreateServiceLinkedRole
[PASS] Root Activity
[PASS] [alert_context] {'sourceIPAddress': '111.111.111.111', 'userIdentityAccountId': '123456789012', 'userIdentityArn': 'arn:aws:iam::123456789012:root', 'eventTime': '2019-01-01T00:00:00Z', 'mfaUsed': None}
[PASS] [dedup] 111.111.111.111:sample-account
[PASS] [title] AWS root activity detected from [111.111.111.111] in account [sample-account]
[PASS] IAMUser Activity
[PASS] Root User Failed Activity
[PASS] Successful Root Login
[PASS] [alert_context] …
```

Add alert_context output

---

panther_analysis_tool/rule.py
tests/unit/panther_analysis_tool/test_rule.py

Relates to https://app.asana.com/0/1200441743569436/1200267145879888
In order to make the changes in https://github.com/panther-labs/panther_analysis_tool/pull/109 easier to review, this PR only copies the files from Panther, without using them anywhere.
* Copy rule executor, importer and result aggregator from Engine, along with their unit tests.
* No additional tests

Copy rule executor and result aggregator from Engine

---

Makefile
panther_analysis_tool/destination.py
panther_analysis_tool/exceptions.py
panther_analysis_tool/main.py
panther_analysis_tool/rule.py
tests/fixtures/detections/destinations/example_available_destination_name.py
tests/fixtures/detections/destinations/example_available_destination_name.yml
tests/fixtures/detections/example_unhandled_exception_on_import.py
tests/unit/panther_analysis_tool/test_main.py
tests/unit/panther_analysis_tool/test_rule.py

Closes https://app.asana.com/0/1200441743569436/1200267145879888
In order to mirror the behavior during of the core rule executor and eventually share the code between Panther Engine and PAT, the corresponding module is being transferred from the Engine here. The previous rule execution logic must be adapted / replaced by encapsulated functionality in the `Rule` class.
* Add an integration test that checks that all detections defined `panther-analysis` pass.
* Allow a path to be passed directly to the `Rule` executor for importing the rule code as module, rather than creating a new temporary file containing the raw code.
* Adapt test setup procedure to instantiate `Rule` and utilize the `RuleResult` for evaluating and displaying execution results. 
* Unit tests
* Run tests on …

Port Panther Rules Engine rule execution logic and flow

---

panther_analysis_tool/main.py
tests/unit/panther_analysis_tool/test_main.py

Closes https://app.asana.com/0/1200543078196176/1200629761291101
The managed schemas sub-commands may confuse users since it is not easy to differentiate between
custom schemas handling and managed schemas operations.
Since they still might be useful in the near future for internally-issued upgrades,
we optionally include the sub-commands only when the `PANTHER_PAT_INCLUDE_INTERNAL_SUBCOMMANDS` variable is present.
* Include `update-schemas` and `zip-schemas` sub-parsers only when a special environment variable is present.
```
$ PANTHER_PAT_INCLUDE_INTERNAL_SUBCOMMANDS=true panther_analysis_tool --help
usage: panther_analysis_tool [-h] [--version] [--debug]
{release,test,publish,upload,update-custom-schemas,update-schemas,zip,zip-schemas}
...
Panther Analysis Tool: A command line tool for …
```

Hide internal sub-commands for managed schemas from help message

---

panther_analysis_tool/log_schemas/user_defined.py
tests/unit/panther_analysis_tool/log_schemas/test_user_defined.py

Closes https://app.asana.com/0/1199906407795548/1200783112556400
An empty response may be returned if no custom schemas are yet stored in the backend.
* Fall back to empty list as a default for existing schema on empty API response.
* Tested end-to-end in conditions where an empty JSON object is returned by the API.

Handle empty results response for existing schemas request

---

panther_analysis_tool/log_schemas/user_defined.py
tests/fixtures/custom-schemas/valid/schema_1_tests.yml
tests/unit/panther_analysis_tool/log_schemas/test_user_defined.py

Closes https://app.asana.com/0/1200693863324520/1200791354082308
Schema tests would be reported as malformed schema definitions, and were skipped but the error reporting results in a non zero exit code.
* Filter discovered files by detecting test case files and omitting them from the path list of files to be examined as possible schema definitions.
* Reproduced the error by adding a test file containing a single document, since YAML parsing would break either way for multidocument YAML files.
* Tested the changes end-to-end to verify that no error is reported.

Detect and ignore schema test case files

---

panther_analysis_tool/detection.py
panther_analysis_tool/rule.py
tests/unit/panther_analysis_tool/test_policy.py
tests/unit/panther_analysis_tool/test_rule.py

Add detection type by default to `DetectionResult`, similar to severity and id. 
* add type by default
* update tests to take into account newly set field
* `make test`

add type by default to detectionresult

---

panther_analysis_tool/detection.py
panther_analysis_tool/main.py
panther_analysis_tool/testing.py
tests/fixtures/detections/example_set_duplicates.yml
tests/fixtures/detections/valid_analysis/policies/example_policy_generated_functions.py
tests/fixtures/detections/valid_analysis/policies/example_policy_generated_functions.yml
tests/unit/panther_analysis_tool/test_rule.py
tests/unit/panther_analysis_tool/test_testing.py

Closes: https://app.asana.com/0/1199961856165998/1201003028086559/f
With dynamic field output in policies, we should show the output for them when running `pat`.  Also, we should use the testing module to be consistent with the BE.
* unify the way we call the run and aux methods between rules and policies
* update output: 
* show dynamic fields for policies
* print rule/policy output or error as well
* Update `FunctionTestResult` to have a per-function `matched` value
* can be used to determine if we should print the detection status/output. (see "example rule / aux function throws error" below for difference in output)
* can be used in the future for output checking on a per function basis
* `make test`
* `make integration`
<details>
<summary> example policy output </summary>
```
% …
```

update policy output

---

panther_analysis_tool/schemas.py
tests/fixtures/custom-schemas/valid/schema-3.yml
tests/unit/panther_analysis_tool/log_schemas/test_user_defined.py
tests/unit/panther_analysis_tool/test_main.py

We have a schema named `Custom.AWS.EKS.Audit` that cannot be used with the PAT test tool. The unit tests will throw an error:
```
[ERROR]: [('./kubernetes_rules/kubectl_exec.yml', SchemaError("Key 'LogTypes' error: LOG_TYPE_REGEX does not match 'Custom.AWS.EKS.Audit'"))]
```
Due to this regex: https://github.com/panther-labs/panther_analysis_tool/blob/fe7fc735b6d62dc585e47349ff58a3dda30961ed/panther_analysis_tool/schemas.py#L54
The rest of the Panther tooling allowed for a schema with this naming scheme to be created and there appears to be precedence for schema names with multiple `.`'s: `Microsoft365\.Audit\.SharePoint`, `Microsoft365\.Audit\.Exchange`.
* expand the allowed regex for custom schemas in the test tool to support schema names with multiple separators.
* Write a test case …

expand regex for allowed Custom schema names

---

README.md

Remove obsolete references to update-lookup-table
* Doc/readme update, lookup tables will be managed with/as Packs going forward
* Just doc

Remove obsolete references to update-lookup-table

---

panther_analysis_tool/backend/public_api_client.py
panther_analysis_tool/cmd/standard_args.py

We had the wrong text for one of our commands and also did not have the ability to provide the full url to an endpoint for the public api
* updates help text around api-host to include references to api documentation
* updates host logic to use raw host if it is a valid url

adds reference to api docs and makes minor modification to public api host logic.

---

tests/fixtures/queries/example-scheduled-query.yml

PAT can support uploading the schedule queries but it is missing the sample. This PR is adding a new sample for the scheduled queries. 
* A scheduled_query sample for PAT under fixtures/queries folder.

Adding a sample scheduled query to the PAT tests

---

tests/fixtures/queries/example-scheduled-query.yml

The scheduled query example missed Tags element so this PR adds the Tags. 
* Added Tags element and removed reference to snowflake and used the generic term, datalake

Added Tags element and removed snowflake reference

---

panther_analysis_tool/backend/graphql/delete_saved_queries.graphql
panther_analysis_tool/backend/public_api_client.py

We are adding support for saved queries via the public api
* adds real implementation of the delete saved queries method of the public api client

adds public api delete saved queries support

---

panther_analysis_tool/backend/client.py
panther_analysis_tool/backend/lambda_client.py
panther_analysis_tool/backend/public_api_client.py
panther_analysis_tool/main.py

The GQL client is very noise at the Info log level.  Raising the log level of the async HTTP transport that it uses.
* Increase log level of AIOHTTP transport to WARNING
* Pretty Print bulk upload response

Logging Updates

---

panther_analysis_tool/backend/public_api_client.py
panther_analysis_tool/cmd/bulk_delete.py

Was parsing incorrect field from GraphQL response
* parse correct field from GraphQL response body

correctly parse saved query names when deleting detections

---

panther_analysis_tool/main.py

Env variables were only read if panther_config.yml existed.  Now the env variables are always parsed.
The variable precedence is now environment > panther_config.yml > command line options
* Environment variables are always parsed

read variables from env

---

panther_analysis_tool/backend/public_api_client.py

Because None was being explicitly set in the return value, the default value was not being returned.

Fix Unexpected NoneType in response

---

panther_analysis_tool/main.py

Remove the required args for Check Connection, so that the arg parser doesn't fail before the environment variables are parsed.

make check conn work with env variables

---

Makefile
panther_analysis_tool/backend/client.py
panther_analysis_tool/backend/graphql/sdk_upload.graphql
panther_analysis_tool/backend/lambda_client.py
panther_analysis_tool/backend/mocks.py
panther_analysis_tool/backend/public_api_client.py
panther_analysis_tool/cmd/configsdk_upload.py
panther_analysis_tool/main.py

This PR implements bulk upload for Config-SDK-based analysis modules. This function is accessible via the `configsdk upload` subcommand, also also runs at the end of the normal `upload` subcommand.
* Initial implemention of the `configsdk upload` command
* Run `configsdk upload` automatically after the normal `upload` process if a `panther_content/__main__.py` file is detected
This initial implementation comes with a few caveats:
* We look at `CWD/panther_content/__main__.py` to discover the user's Config-DK-based analysis module. Other paths are not supported.
* The lambda-based API doesn't currently support this feature, so this new function only supports usage via the public API via API token.

Add bulk upload for Config-SDK-based analysis modules

---

.circleci/config.yml

Our `make ci` target [already runs the `integration` target](https://github.com/panther-labs/panther_analysis_tool/blob/master/Makefile#L3), so running the `integration` target again via CircleCI just results in running the same target twice.
You can confirm that by searching the full output from [the successful CI run on my last PR](https://app.circleci.com/pipelines/github/panther-labs/panther_analysis_tool/1091/workflows/da316e1c-6dfe-485a-be77-1cbaa683b81f/jobs/1052) for the string `Testing analysis items in tests/fixtures/detections/valid_analysis`, which occurs twice.
* CircleCI config does not explicitly run `make integration`
* Look at CI output and verify `make integration` target is run once

CI: don't run `make integration` target twice

---

panther_analysis_tool/backend/client.py
panther_analysis_tool/backend/lambda_client.py
panther_analysis_tool/cmd/configsdk_upload.py
panther_analysis_tool/main.py

Config sdk uploads only work with the public-api this adds support for direct lambda invocations. 
* updates lambda client to support config uploads
* updates lambda client to handle json decode better ... just presents the response to the user now .. which will be way more actionable than a cryptic json exception message we were showing before
* adds aws-profile arg to the config upload command
* removes checks around config-sdk that forced api only usage
* manual uploads
* unit tests

[config sdk] adds support for direct lambda invocations.

---

panther_analysis_tool/main.py
setup.py

https://app.asana.com/0/1200908948600035/1202486395033678/f
* Remove LUTS_LOCATION option when zipping file
* Specifying path - selects only the files in that path 
* Specifying all - includes all files 
* Specifying luts - includes only luts file path

Path specification fix for PAT tool

---

panther_analysis_tool/main.py
setup.py

LUTS are never excluded by filters, so setting a filter like `--filter AnalysisType=policy,rule` will still include LUTS. Also, the LUTS file paths are always included as part of `search_directories` in `test_analysis`.
This change removes them from the list of always included paths for `test_analysis` and prevents filter_analysis from always returning `True` when dir_name matches `*lookup_tables*`

Do not always include LUTS

---

panther_analysis_tool/analysis_utils.py
panther_analysis_tool/constants.py
panther_analysis_tool/main.py
panther_analysis_tool/zip_chunker.py
tests/unit/panther_analysis_tool/test_main.py

Closes https://app.asana.com/0/1202324455056256/1203717883565327/f
We need the ability to break our uploads into smaller pieces to avoid timeouts.
* Moves some constants in the main.py to its own file
* Moves some functions in main.py to its own file
* Adds new zip chunking capability
* Adds --batch parameter to uploads .. when set will break uploads into chunks of
- rules, policies, globals, data models, packs
- queries & scheduled rules
- look up tables
* Updates zipping logic to use relative paths instead of absolute paths for stored zip files
* unit tests
* manual uploads
**Command:** `panther_analysis_tool upload --skip-tests --batch`
```bash
[INFO]: Zipping analysis items in . to .
[INFO]: Uploading Batch 1...
[INFO]: Uploading items to Panther
[INFO]: Upload success.
[INFO]: API …
```

adds upload chunking support via the --batch parameter

---

panther_analysis_tool/main.py

We check that Alarm is not longer than one day. The backend includes precisely one day into acceptable value. Fixing PAT tests to comply.
- AlarmPeriodMinutes <= 1440 (instead of <)

AlarmPeriodMinuted should be not greater than 1 day (Fixing < to <=)

---

.github/workflows/ci.yml

The CI check needs to run on PRs. This should unblock PRs created via forks.
* Sets `on` to `[push, pull_request]`
* Check runs successfully after PR is opened

Run CI Workflow on PRs

---

.github/workflows/ci.yml

Adds the `pull_request_target` trigger to allow formatted files to be committed to a target branch (including forks).
https://github.com/stefanzweifel/git-auto-commit-action/blob/master/README.md#workflow-should-run-in-forked-repository
* Adds `pull_request_target` to the CI Workflow triggers

Add pull_request_target

---

.github/workflows/ci.yml
.github/workflows/fmt.yml

We want fmt to operate on pull_request_target to allow fmt changes to be committed to forked PRs, but we do not want ci to operate on pull_request_target because this requires that tests pass on the tip of master which is not guaranteed because the tests depend on changing resources.
* Move fmt job from ci.yml to fmt.yml
* Add pull_request_target to fmt.yml
* Testing will be GitHub CI

Split ci and fmt into separate workflows with different targets

---

panther_analysis_tool/schemas.py
tests/unit/panther_analysis_tool/test_schemas.py

Adds Zeek Schemas to `LOG_TYPES_REGEX`.
Following up comment from [this PR](https://github.com/panther-labs/panther-enterprise/pull/12291).
Relates to https://app.asana.com/0/1203154630469853/1204484925017214/f
* Added unit test to validate all Zeek schemas.

feat: add Zeek schemas to LOG_TYPES_REGEX

---

panther_analysis_tool/backend/client.py
panther_analysis_tool/backend/errors.py
panther_analysis_tool/backend/graphql/async_bulk_upload.graphql
panther_analysis_tool/backend/graphql/async_bulk_upload_status.graphql
panther_analysis_tool/backend/graphql/introspection_query.graphql
panther_analysis_tool/backend/lambda_client.py
panther_analysis_tool/backend/mocks.py
panther_analysis_tool/backend/public_api_client.py
panther_analysis_tool/main.py

When using the api token upload requests are limited to 30seconds. Since they are cases where an upload can take more than 30 seconds we need a way to allow users to continue to upload without any timeout issues.
* Updates upload requests that are using the api token to use async uploads
* Adds new --no-async flag to the upload command
* Add logic to detect if panther instance supports async bulk uploads
* Fixes bug where we would always retry uploads vs only retrying when needed
* Lots of manual tests

adds async bulk upload support for api users

---

panther_analysis_tool/schemas.py

adds mongdodb organization and project event log type to regex
See #292.
* This PR is a temporary work around for the failing asana CI task that the original PR ran into 
* Manually verified that these new log types work

adds mongdodb organization and projectevent log type support

---

README.md

Github README markdown allows to easily copy bash commands to execute in local env. 
The problem was that the commands we have listed include `$` which gets copied as well... I had to click on copy, then paste on terminal, then move the curson backwards to delete the extra `$`. I think it's easier to just... remove it all together. 
* Removing `$` from the beginning of commands that are meant to be copy/pasted. 
none. README changes.

Fixing README to make it easier to copy/paste commands

---

panther_analysis_tool/command/benchmark.py

Fixup bug introduced in PAT `benchmark` while trying to follow ci recommendations
* Only calculate params once
* Manual test of `benchmark` before and after change

Dana katzenelson perf test

---

panther_analysis_tool/command/benchmark.py

It was pointed out that listing all of the files in the dir was unwieldy for large file counts and that advice on how to use the method would be preferable
closes: https://app.asana.com/0/1200908948600035/1205226048539595/f
* Cleaned up error text for too many detections and wrong type
* Ran manually and observed error
* Ensured existing unit tests pass

Improve error messages for bad file cases

---

panther_analysis_tool/main.py

Ensure that the text that displays per-subcommand when running `panther_analysis_tool --help` also displays when running `panther_analysis_tool subcommand --help`. Provides useful context about the subcommands
* duplicate subparser help as description
* add arg default values to help output
* Manually checked that output appeared

Display subcommand help text on subcommand help (as description)

---

panther_analysis_tool/schemas.py
panther_analysis_tool/validation.py
tests/unit/panther_analysis_tool/test_schemas.py

The UI allows you to create a policy without resource types. This equates to a policy that looks at all resources. This update adjusts the PAT schema to match behavior in panther.
* Allows resource types to be optional for policies

allows resource types to be optional

---

panther_analysis_tool/backend/client.py
panther_analysis_tool/backend/public_api_client.py
panther_analysis_tool/cli_output.py
panther_analysis_tool/command/validate.py
panther_analysis_tool/main.py
panther_analysis_tool/validation.py
tests/unit/panther_analysis_tool/test_main.py

The validate cmd introduced some nicer error messaging. This PR gets upload to use that same messaging.
* Improves upload errors by matching validate errors
* Formats errors here and there to match the rest of the app
Manual

Upload and validate error improvements/alignment

---

.github/CODEOWNERS

We no longer have a Security Team, so we should not block version bumps on them anymore
* Remove CODEOWNERS reference to Security Team
* N/A

Remove CODEOWNERS entry for now-nonexistent Security Team

---

setup.py

While troubleshooting a bug, i noticed that our PYPI page is missing any information. This just ports our README over to the pypi description.
Just look at em
* Prior to the next release, we should deploy to TestPyPi to verify we're good.

add README to pypi description

---

.github/workflows/version_bump_pr.yml

* when running `gh` to create a PR in non-interactive mode, the body flag is required. This PR adds the body flag.

Adding body flag to version bump GHA

---

.github/workflows/version_bump_pr.yml

GITHUB_TOKEN cannot trigger other GHA's, we have `fmt` and `ci` as required checks on PR's, switching to a PAT will allow those GHA's to trigger on PR's created by a PAT (not GITHUB_TOKEN)

Switching to PAT for GH_TOKEN

---

panther_analysis_tool/main.py

When we introduced the `saved_query` type a few months back it came with a bug that prevented a user from having multiple saved queries stored in their repo
* Updates our logic to properly use the query name field as a unique id
* Manual testing to verify behavior

fixes bug that prevented multiple saved queries from being uploaded

---

panther_analysis_tool/schemas.py

We had previously disallowed defining tests in a derived detection YAML. This change reverts that decision as defining tests is a safe operation, even if inheritance is not supported for tests right now.
* Added `Tests` to the Schema governing the list of valid keys in a derived detection YAML
* Manually tested uploading a derived detection with tests

Whitelisting 'tests' as an allowed field in derived detection YAML

---

panther_analysis_tool/schema_regexs.py
tests/unit/panther_analysis_tool/test_schemas.py

Removing references to Azure.SignIn schema. 
All related detections are already removed as seen [here](https://github.com/panther-labs/panther-analysis/pull/953) and discussed [here](https://panther-labs.halp.com/tickets/6024). 
* Removing `Azure.SignIn` from list of allowed schemas

Removing references to Azure.SignIn schema

---

panther_analysis_tool/analysis_utils.py
panther_analysis_tool/main.py

With inheritance there's a UX issue where a user could have a base detection and a derived detection enabled at the same time, creating duplicate alerts for each event that matches the base detection's logic. We wish to give users a convenient option to not have to remember to disable a base detection when creating a derived detection from it. This manifests as a:
- `--auto-disable-base` CLI option
- as well as a `auto_disable_base: true` option in the `.panther_settings.yml` file
* adds option to auto disable base
* when true, for every derived detection, find the base detection, and set `Enabled: false` in the base detection yaml file prior to uploading
* tested e2e in dev env.
* tested with CLI arg and `auto_disable_base: true` in `.panther_settings.yml`
*

adds option to auto disable base

---

panther_analysis_tool/analysis_utils.py
panther_analysis_tool/backend/client.py
panther_analysis_tool/backend/graphql/get_rule_body.graphql
panther_analysis_tool/backend/lambda_client.py
panther_analysis_tool/backend/mocks.py
panther_analysis_tool/backend/public_api_client.py
panther_analysis_tool/main.py
tests/fixtures/derived_without_base/derived.yml
tests/fixtures/tests_can_be_inherited/base.py
tests/fixtures/tests_can_be_inherited/base.yml
tests/fixtures/tests_can_be_inherited/derive.yml
tests/unit/panther_analysis_tool/test_main.py

We wish to add testing support to derived detections, and therefore PAT test must take derived detections into account.
* PAT test can lookup base detections if its referenced in a derived detection that is being tested
* PAT test can test overrides of a derived detection
* PAT test can inherit base test cases if no overrides are provided
* added unit tests
* tested manually in dev env with PAT

DAC-501 PAT can test derived detections w/ inheritance and overrides

---

panther_analysis_tool/main.py
tests/unit/panther_analysis_tool/test_main.py

if user is using the old lambda client, this will throw an exception, breaking the upload.
* we check for this exception and catch it

fix feature flags not checking for lambda exception

---

setup.py

Why is this chunk of code in there? I have always wondered
I noticed panther-detection-helpers isn't in the requirements but should be

adding pdh and removing dead code from setup

---

setup.py

I added PDH as an install_requires but it definitely isn't. I have been really confused today.

Removing PDH because it isn't used in this project

---

panther_analysis_tool/main.py

We need to ignore Rules that contain the `Configuration Required` from Pack checks. This will also require that Packs containing these rules already be updated to not include these rules.
* Ignores Rules that contain the `Configuration Required` Tag
* Tests pass as expected

Omit rules with Configuration Required Tag from Pack check

---

panther_analysis_tool/backend/graphql/async_bulk_upload_status.graphql
panther_analysis_tool/backend/graphql/bulk_upload.graphql

Correlation rule statistics were being returned from bulk upload, but the data wasn't actually being populated. 
* Added correlation rules to both types of bulk upload
* Manually tested

adding correlation rules to async bulk upload graphql

---

README.md

Formats the `README.md` file and cleans up linter errors.

Format README and clear markdown linter errors

---

panther_analysis_tool/main.py

Disabled rules do not have to be in any pack. This PR updates `check-packs` to ignore disabled rules.

Ignore disabled rules during packs-check

---

Pipfile
Pipfile.lock

Last PR I merged in downgraded this version for some reason .. went ahead and upgraded it back and updated responses to be pinned
* aiohttp updated to 3.9.2
* responses dev dependency pinned to 0.25.0
* Local
* CI

update aiohttp to 3.9.2 and pin responses version.

---

panther_analysis_tool/detection_schemas/analysis_config_schema.json
panther_analysis_tool/schemas.py
tests/unit/panther_analysis_tool/test_schemas.py

we wish to support PAT testing CR unit tests in the future. this PR is a primer for that: supporting the schema prior to adding explicit test support.
* schema update to support CR unit tests
- uploading a CR yaml file w/ unit tests works:
```
Panther CLI Test Summary
Path: ./rules/mycorr
Passed: 1
Failed: 0
Invalid: 0
[INFO][root]: Zipping analysis items in ./rules/mycorr to .
[INFO][root]: Uploading items to Panther
[INFO][root]: API Response:
{
"rules": {
...
```

update schemas to support cr unit tests

---

panther_analysis_tool/directory.py
panther_analysis_tool/main.py

If multiple instances of PAT are invoked users can see unexpected behavior as multiple processes can share the same paths causing various race conditions. 
- each instance of PAT gets its own temp folder
- at process exit we remove the directory
* manually tested running the following commands in parallel
* `pipenv run pat upload --skip-tests`
* `pipenv run pat upload`
* `pipenv run pat test`

adds logic to improve temp directory management

---

panther_analysis_tool/analysis_utils.py

We have a pattern for ignoring files and this needs to be extended to include `dependabot.yml` since PAT treats any JSON or YAML files as valid files.
* Adds `dependabot.yml` to `ignored_normalized`
* Checks pass as expected

Ignore dependabot.yml

---

.github/workflows/asana.yml
.github/workflows/ci.yml
.github/workflows/fmt.yml
.github/workflows/test_release_publish.yml
.github/workflows/version_bump_pr.yml
panther_analysis_tool/backend/client.py

Relates to EPD-368
This PR adds StepSecurity's `harden-runners` Action to all of our Workflows. 
We'll run egress blocks for Workflows that can be validated within a PR and audits for the other Workflows. Once the latter run at least once, we can implement the recommendations in a follow-up PR.
- Adds the `harden-runner` Action to all Workflows
- Checks pass as expected

Use harden-runner Action for all Workflows

---

.github/workflows/fmt.yml

This PR uses Chainguard's `setup-gitsign` action to sign our `fmt` commits via Gitsign so that we can verify that `panther-bot-automation` did indeed make the change.
Trust, but verify!

Sign fmt commits via gitsign

---

.github/workflows/fmt.yml

This was blocked by StepSecurity:
We need this for Gitsign to work correctly.
Relates to: EPD-429
* Allows egress for `fulcio.sigstore.dev` via HTTPS
* N/A

Allow fulcio egress for Gitsign

---

.github/workflows/ci.yml
.github/workflows/fmt.yml
panther_analysis_tool/log_schemas/user_defined.py

We need a couple more allows for Gitsign to work properly. This PR adds them.
* Allows `rekor.sigstore.dev` and `tuf-repo-cdn.sigstore.dev:443`
* [`96ed7e9` (#517)](https://github.com/panther-labs/panther_analysis_tool/pull/517/commits/96ed7e9ab54f5a5e7c101b05512ed47a96057092)

More egress allows for fmt

---

.github/workflows/fmt.yml

Good catch @c0nfleis!
* Adds `443` to the `rekor.sigstore.dev` rule
* N/A

Add missed port to egress rule

---

panther_analysis_tool/backend/client.py
panther_analysis_tool/main.py
tests/unit/panther_analysis_tool/backend/test_lambda_client.py

Direct lambda invoke bulk upload was failing because we added a new output field `deleted`. Also fixes a problem when running in batch mode where we were not printing out the error if the upload failed.
fix it
Added unit test and manually confirmed I can upload with this change

fix direct lambda upload

---

Makefile

We recently started seeing failures when running the make test command, even when navigating back to old commits. This is likely due to some runtime change on the github action side. 
While this removes the test command it retains the integration command which continues to work; a deeper investigation is needed to understand why make test has recently started failing.
This change makes it so we can unblock other PRs and still have reasonable confidence in our changes since we'll still have integration tests running
* Removes the test command from the ci command
* Lots of manual testing locally and via github action

removes test command from ci job

---

.github/workflows/test_release_publish.yml

We still need to get to the bottom of the unit test issue we've been seeing. In the mean time we'll update our release job to run integration tests instead.
* updates release job to run integration tests

updates release job to run integration test instead of unit tests

---

panther_analysis_tool/main.py

PAT test currently prints all test results, with an option to sort them to the bottom of the result list. This sucks for github because you have to scroll through thousands of lines in a github action to see what test(s) failed. This PR adds a flag to only print failed test results, so the output is minimal and easy to grep.
* introduced `--print-failed-only` flag
* `make tests` works
* manually tested with/without flag

add option to print only failing unit tests

---

panther_analysis_tool/validation.py
tests/unit/panther_analysis_tool/test_validation.py

https://panther-labs.slack.com/archives/C0719AH18SV/p1731965902688019
* Adds handling of simple dict table parse case
* Added unit test using example provided that failed before and passes now
* Not sure if it works in all cases, but it took a while for any customer to complain about this case, so we can fix future cases as the need arises

Fix broken sql table name validation example

---

.github/workflows/test_release_publish.yml
Makefile
panther_analysis_tool/main.py
tests/unit/panther_analysis_tool/test_main.py

Tests were failing due to filesystem issues when running on macOS:
_DATAMODEL_FOLDER was sometimes created as a file instead of a directory
The tearDown method was trying to remove files without checking if they exist
The --max-retries argument was too restrictive, causing test failures with negative values
Added checks to ensure _DATAMODEL_FOLDER is a directory, removing it if it's a file
Added proper directory creation with os.makedirs(_DATAMODEL_FOLDER, exist_ok=True)
Improved tearDown robustness by checking if files exist before removing them
Removed the choices constraint from --max-retries argument
Added validation in the upload_zip function to handle negative values and values over 10
Reverts https://github.com/panther-labs/panther_analysis_tool/pull/532 and …

Fix filesystem-related errors in test suite

---

panther_analysis_tool/zip_chunker.py
tests/unit/panther_analysis_tool/test_zip_chunker.py

This addresses an issue with batch chunking where dependent files that were referenced by more than one analysis item might not be included in the upload chunk.
* fix to the chunker to track files that have more than one parent
* Added unit tests that were failing before I fixed this issue

fix batch chunking issue

---

.github/workflows/fmt.yml

* skip fmt workflow (the one where we need to import GPG key) for Dependabot PRs
* https://github.com/panther-labs/panther_analysis_tool/pull/619 - this PR is dependabot pr rebased on the current branch and it shows that this approach works

THREAT-525-fix-Dependabot-GPG-key-issue

---

panther_analysis_tool/analysis_utils.py
panther_analysis_tool/main.py

**THIS IS POTENTIALLY A BREAKING CHANGE.**
PAT currently has the undocumented behaviour of treating all JSON files in the repo as YAML files, meaning they will cause errors when they are missing fields like `AnalysisType`. This is problematic for a few reasons, since JSON files are often used for vscode configs, PAT configs, and most importantly, as data files for LUTs.
This behaviour seems to be left over from the original implementation of Panther with CI/CD. There's been no justification since in the code base for why we support this, and none of our guides or documentation suggest customers use JSON spec files over YAML spec files. Therefore it seems safe to assume this is leftover functionality from a time when we envisioned customers may wish to choose between YAML and JSON, and is …

Allow JSON files to be used for LUT data

---

panther_analysis_tool/main.py
panther_analysis_tool/schemas.py
tests/unit/panther_analysis_tool/test_main.py
tests/unit/panther_analysis_tool/test_schemas.py

[A previous PR](https://github.com/panther-labs/panther_analysis_tool/pull/600) added enforced upper and lower bounds for the `DedupPeriodMinutes` spec field to match the options in the UI. However, despite the limits in the UI, Panther's backend doesn't disallow any positive values.
The backend behaviour is:
- `DedupPeriodMinutes` < 5: Silently treat it as 5
- `DedupPeriodMinutes` > 1440: Dedup according to the provided value; i.e. backend enforces no upper limit
This PR removes the failed upload for breaching either limit, and adds a warning if the specified dedup value is under 5 to inform the customer the behaviour they experience may be unexpected.
Internal: See [ASK-2325](https://panther-labs.atlassian.net/browse/ASK-2325) for more context.
* remove schema validation of …

ASK 2325: Remove DedupPeriodMinutes limits
